name: Read hello.txt File

on:
  push:
    branches:
      - main

jobs:
  read-hello-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Read and output content of hello.txt
        run: |
          cat hello.txt
